name: test

on:
  push:
    branches: [ "main", "pytest"]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

  test:
    needs: build 
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
            os: [ubuntu-latest, windows-latest]
            python-version: ["3.9", "3.10", "3.11"]
      fail-fast: false
          
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
  
      - name: Run test for successful worksheet creation
        run: pytest -v -k test_for_successful_worksheet_creation
  
      - name: Run test for column names
        run: pytest -v -k test_for_column_names
  
      - name: Run test for column datatypes
        run: pytest -v -k test_for_column_datatypes
  
      - name: Run test for data validation
        run: pytest -v -k test_for_data_validation
      - name: Check test coverage
        run: pytest test_main.py --cov-config=.coveragerc --cov=main 


