name: test

on:
  push:
    branches: [ "main", "pytest"]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

test:
  runs-on: ubuntu-latest
  needs: build
  steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 

    - name: Run test for successful worksheet creation
      run: pytest -v -k test_for_successful_worksheet_creation

    - name: Run test for column names
      run: pytest -v -k test_for_column_names

    - name: Run test for column datatypes
      run: pytest -v -k test_for_column_datatypes

    - name: Run test for data validation
      run: pytest -v -k test_for_data_validation


      - name: Test coverage (Optional)
        run: |
          pip install coverage
          coverage run -m unittest discover
          coverage report --fail-under=60 # Fails if test coverage is below 60%
